site_name: George 的知识库
site_author: George Cao
site_url: https://georgec6.github.io/Mkdocs-test/
site_description: George's knowledge base

#repo_name: Mkdocs-test
#repo_url: https://github.com/GeorgeC6/Mkdocs-test

copyright: Copyright &copy; 2024 <a href="https://github.com/GeorgeC6" target="_blank" rel="noopener noreferrer">George Cao</a>

theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  favicon: images/favicon.ico
#  apple-touch-icon: images/Just LOGO.png
  icon:
    logo: material/bookshelf
    repo: fontawesome/brands/github
  custom_dir: overrides
  features:
    - header.autohide # 向下滚动时自动隐藏header
    - navigation.tracking # 导航栏跟踪滚动
    - navigation.tabs
#    - navigation.sections
    - navigation.top
    - navigation.indexes  # 点击小节名字自动显示 index 界面
    - toc.integrate
    - toc.follow  # 右侧目录跟随滚动
    - search.highlight
    - search.share
    - search.suggest
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GeorgeC6
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCq09adFYMyB4gRaUFYnVmhQ
    - icon: fontawesome/brands/soundcloud
      link: https://soundcloud.com/gorco
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/413263041

  analytics:
    provider: google
    property: G-BKHW17C33B

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.mark:
      smart_mark: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - admonition
  - footnotes
  - md_in_html
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - search
  - minify:
      minify_html: true # 好像能加快网页加载速度？!

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js # MathJax 3
  - http://tikzjax.com/v1/tikzjax.js

extra_css:
  - stylesheets/extra.css

nav:
  - 主页: "index.md"
  - 数学:
    - "微积分（甲）I":
      - "Math/Calculus I/index.md"
    - "微积分（甲）II": 
      - "Math/Calculus II/index.md"
      - "专题讨论": 
        - "Math/Calculus II/专题讨论/index.md"
        - "关于级数1/n^2的讨论": "Math/Calculus II/专题讨论/关于级数1:n^2的讨论.md"
    - "线性代数": "Math/Linear-Algebra/intro.md"
    - "Special Functions: From Combinatorics to Calculus": 
      - "Math/Special-Functions/index.md"
      - "Week 1: Bernoulli Polynomials": "Math/Special-Functions/Week 1/index.md"
      - "Week 2: Bernoulli Numbers & Generating Function": "Math/Special-Functions/Week 2/index.md"
      - "Week 3: Taylor Polynomials & Taylor Series": "Math/Special-Functions/Week 3/index.md"
      - "Week 4: The Zeta Function": "Math/Special-Functions/Week 4/index.md"
      - "Week 5: The Gamma Function": "Math/Special-Functions/Week 5/index.md"
      - "Week 6: Convexity of Gamma Function": "Math/Special-Functions/Week 6/index.md"
      - "Week 7: Applications of Gamma Function": "Math/Special-Functions/Week 7/index.md"
      - "Week 8: Approximation of Gamma Function": "Math/Special-Functions/Week 8/index.md"
  
  - 物理:
    - "大学物理（甲）I": "Physics/Physics I/intro.md"
    
  - 编程语言:
    - Python: 
      - 前言: "Prog-lang/Python/intro.md"
      - 第零章 Python拾级: "Prog-lang/Python/Chapter 0.md"
      - 第一章 数据类型与运算符: "Prog-lang/Python/Chapter 1.md"
      - 第二章 常用函数: "Prog-lang/Python/Chapter 2.md"
      - 第三章 条件和循环: "Prog-lang/Python/Chapter 3.md"
      - 第四章 算法简介: "Prog-lang/Python/Chapter 4.md"
    
    - C: "Prog-lang/C/C 学习笔记.md"

    - LaTeX: 
      - "Prog-lang/LaTeX/index.md"
      - 资料: "Prog-lang/LaTeX/Resources/index.md"

  - 音乐:
    - "Music/index.md"
    - "音乐理论": "Music/Music Theory/index.md"
    - "音乐制作": "Music/Music Production/index.md"